spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icd10?serverTimezone=UTC
    username: root
    password: marek
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  security:
#    logout:
#      logout-success-url: /login
